@hostname = https://fullstackopen-part3-ncrg.onrender.com
@endpoint = api/persons

@host = {{hostname}}/{{endpoint}}


### GET /persons
GET {{host}} HTTP/1.1


### GET /persons/:id 

GET {{host}}/66ca103c6ea3a01a1fa31540 HTTP/1.1


### GET /persons/:id doesn't exist
GET {{host}}/66ca103c6ea3a01a1fa31543 HTTP/1.1

### POST /persons
POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "name": "john",
    "number": "040-1234576"
}

### DELETE /persons

DELETE {{host}}/66cb462e10846614fb9d5dd2 HTTP/1.1



### PUT /persons/:id

PUT {{host}}/66cb94f8cc58d074faf0d2df HTTP/1.1
Content-Type: application/json

{
    "name": "john",
    "number": "040-1234563"
}