@hostname = fullstackopen-part3-ncrg.onrender.com
@endpoint = api/persons

@host = https://{{hostname}}/{{endpoint}}


### GET /persons
GET {{host}} HTTP/1.1


### GET /persons/:id

GET {{host}}/1 HTTP/1.1


### GET /persons/:id doesn't exist
GET {{host}}/20 HTTP/1.1

### POST /persons
POST {{host}} HTTP/1.1
Content-Type: application/json

{
    "name": "john",
    "number": "040-123456"
}

### DELETE /persons

DELETE {{host}}/197 HTTP/1.1
